# Generated by Django 4.0.4 on 2024-05-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='user',
        ),
    ]
