# Generated by Django 4.0.4 on 2024-05-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_borrowing_book_remove_borrowing_user'),
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='borrowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowings.borrowing'),
        ),
        migrations.DeleteModel(
            name='Borrowing',
        ),
    ]
